services:
  lanyuechat:
    build:
      context: .
      dockerfile: Dockerfile
    image: harbor.houmo.ai/application_software/lanyuechat:v1.2.0-daily20250903
    container_name: lanyuechat
    volumes:
      - ./data/backend:/app/backend/data
    ports:
      - 3000:8080
    # env_file:
    #   - .env
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
